# Generated by Django 5.2 on 2025-05-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ciudad_created_at_ciudad_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
